services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models  
      - ./data:/app/data      
    environment:
      - MODEL_PATH=/app/models/epilepsy_model.keras
      - DATA_PATH=/app/data/patients/patients_data_updated.csv
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri /mlruns --host 0.0.0.0

  trainer:
    build:
      context: .
      dockerfile: services/model_training/Dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./metrics:/app/metrics
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DATA_PATH=/app/data
      - MODEL_PATH=/app/models
      - METRICS_PATH=/app/metrics

  preprocessor:
    build:
      context: .
      dockerfile: services/preprocessing/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data

  patient_data_puller:
    build:
      context: .
      dockerfile: services/patient_data_pull/Dockerfile
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data
  