services:
  api:
    build:
      context: .
      dockerfile: data/Dockerfile
    container_name: epilepsy_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONPATH: /app
