stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - data/raw/Epileptic_Seizure_Recognition.csv
    outs:
      - data/processed/X_train.npy
      - data/processed/Y_train.npy
      - data/processed/X_test.npy
      - data/processed/Y_test.npy
      - data/patients_data.csv
      
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.npy
      - data/processed/Y_train.npy
    outs:
      - models/epilepsy_model.h5