stages:
  preprocess:
    cmd: docker-compose run --rm preprocessor
    deps:
      - data/raw/Epileptic_Seizure_Recognition.csv
    outs:
      - data/processed/X_train.npy
      - data/processed/Y_train.npy
      - data/processed/X_test.npy
      - data/processed/Y_test.npy

  train:
    cmd: docker-compose run --rm trainer
    deps:
      - data/processed/X_train.npy
    outs:
      - models/epilepsy_model.keras