FROM python:3.9-slim

WORKDIR /app

COPY services/patient_data_pull/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/patient_data_pull /app
COPY data /app/data

CMD ["python", "patient_data_pull.py"]