FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY services/preprocessing/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy code
COPY services/preprocessing /app
COPY data /app/data

# Create directories
RUN mkdir -p /app/data/processed /app/data/patients

CMD ["python", "preprocessing.py"]